name: Test PowerShell on Ubuntu
on: push

jobs:
  build:
    name: Pester
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Perform a Pester test from the Tests.ps1 file
      shell: pwsh
      run: |
        invoke-psake psakefile